### ISSUE TITLE
Missing requirement in requirement.txt

### ISSUE THREAD

**Issue by lowks** [lambdalisue/notify#3]
Since there is a usage of `keyring` in the code, shouldn't this be a line in `requirements.txt` ?

**Comment by lambdalisue** [comment]
Did you get error message? While
1. `keyring` is required only when authentication is required
2. There is an alternative way and it automatically use that https://github.com/lambdalisue/notify/blob/master/src/notify/compat.py#L13

**Comment by lambdalisue** [comment]
But well yeah, you right. I add note in README

**Comment by lambdalisue** [comment]
I added: https://github.com/lambdalisue/notify/commit/ea24287a35b5028c1bdf4a90be79f97c5470bef3
